trigger:
  - master
pr:
  - master

pool:
  vmImage: 'Ubuntu-20.04'

resources:
  repositories:
    - repository: templates
      type: github
      name: vorkos/ado-templates  
      endpoint: vorkos

jobs:
  - template: dry/tf-check.yml@templates